import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TelegramProvider } from "@/context/TelegramContext";
import Script from "next/script";
import Providers from "./providers";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Providers>
        <TelegramProvider >
          
            <div className="flex flex-col items-center">
              <main id="main-content"
                className={
                  `flex-1 w-full max-w-[452px] m-auto px-4 pt-4 pb-[calc(var(--footer-height)+env(safe-area-inset-bottom))] pt-safe px-safe`}>
                {children}
              </main>
              <Footer />
            </div>
          
        </TelegramProvider>
        </Providers>
      </body>
    </html>
  );
}
