name: Deploy to Vercel

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL:               ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY:       ${{ secrets.SUPABASE_SERVICE_KEY }}
      NEXT_PUBLIC_SUPABASE_URL:   ${{ secrets.SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      OPENAI_API_KEY:             ${{ secrets.OPENAI_API_KEY }}
      PLISIO_API_KEY:             ${{ secrets.PLISIO_API_KEY}}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.local
        run: |
          cat <<'EOF' > .env.local
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          PLISIO_API_KEY=${{ secrets.PLISIO_API_KEY}}
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          EOF

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN_PROMPTBUYER }} --yes
